server:
  port: 8090
  servlet:
    context-path: /clinica

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicadb
    username: clinica_user
    password: Clinica2025!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: clinica
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true